application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /html
  static_dir: html

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: classroom.app
  secure: always

libraries:
- name: jinja2
  version: latest